# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title			: A Curious Engineer
description		: Do it right or not at all.
baseurl			: ""
url			: ""
github_username		: MKDonnelly
breadcrumbs		: true
search			: true
search_full_content	: true
paginate		: 10
paginate_path		: /page:num/

Matthew Donnelly:
  name		: "Matthew Donnelly"
  avatar	: "/assets/images/matthew-donnelly-avatar.jpeg"
  bio		: "I am a software engineer that specializes in backend development using Python 3, Flask, SQLAlchemy, and AWS"
  location	: "California"
  email		: "brilliantrocketscientist@outlook.com"
  uri		: "https://MKDonnelly.github.io"
  github	: "MKDonnelly"
  linkedin	: "mkdonnelly"

# Build settings
#theme: mmistakes/minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
